version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: echo "yarn installing"
      - run: yarn install
      - run: yarn run build

  hello_test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: echo "helloooo!"

workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hello_test
